services:
  - type: web
    name: college-django-app
    runtime: python
    buildCommand: pip install -r server/requirements.txt && python server/manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn server.config.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
